version: '3.7'

services:
  rsshub:
    image: diygod/rsshub
    ports:
      - 1200:1200
    restart: always
    environment:
      - NODE_ENV=production
  huginn:
    image: huginn/huginn
    ports:
      - 3000:3000
    restart: always
  melody:
    image: foamzou/melody:latest
    ports:
      - 7003:5566
    volumes:
      - ~/.local/melody-profile:/app/backend/.profile
    restart: always
