version: '3.7'

services:
  rsshub:
    image: diygod/rsshub
    ports:
      - 1200:1200
    restart: always
    environment:
      - NODE_ENV=production
  huginn:
    image: huginn/huginn
    ports:
      - 3000:3000
    restart: always
